package domain

import (
	"crypto/rand"
	"encoding/hex"
	"time"
)

// NewUUIDv7 generates a version 7 (time-ordered) UUID for first-class control-plane
// resources (CanonicalEntity, Mapping, MappingScope, Market, DigitalEstate, Engine,
// EngineInstance, Capability, CapabilityBinding, IsolationProfile, OutboxEvent,
// AuditRecord and similar), per BCP-DB-001/BCP-GO-001 (docs/adr/ADR-BCP-001-...md,
// sections 4 and 30-31): "All first-class Control Plane resources SHALL use UUIDv7
// generated by the Go application ... PostgreSQL 17's native gen_random_uuid()
// generates UUIDv4, so it must not be relied on as the identifier source."
//
// Layout (RFC 9562):
//
//	48 bits  unix_ts_ms   (big-endian milliseconds since the epoch)
//	4  bits  version      (0111)
//	12 bits  rand_a
//	2  bits  variant      (10)
//	62 bits  rand_b
func NewUUIDv7() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// crypto/rand failing is treated as a programming/environment error per
		// section 4.4 ("A missing application-generated ID should normally be
		// considered a programming error"); callers should not persist this
		// sentinel, but a zero-value random tail is preferable to a panic on
		// the request path.
	}
	ms := uint64(time.Now().UnixMilli())
	b[0] = byte(ms >> 40)
	b[1] = byte(ms >> 32)
	b[2] = byte(ms >> 24)
	b[3] = byte(ms >> 16)
	b[4] = byte(ms >> 8)
	b[5] = byte(ms)
	b[6] = (b[6] & 0x0f) | 0x70 // version 7
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10

	encoded := hex.EncodeToString(b[:])
	return encoded[0:8] + "-" + encoded[8:12] + "-" + encoded[12:16] + "-" + encoded[16:20] + "-" + encoded[20:32]
}
